use bankingdb;
show tables;
use bankingdb;
show tables;
use bankingdb;
drop table customers;
create table Customers (
CustomerID INT Primary Key,
FirstName VARCHAR(50),
LASTNAME VARCHAR(50),
EMAIL VARCHAR(100),
PHONE VARCHAR(15),
ACCOUNTCREATIONDATE date
);
DESC CUSTOMERS;
CREATE TABLE ACCOUNTS (
ACCOUNTID INT,
ACCOUNTTYPE VARCHAR(20),
BALANCE DECIMAL(10,2)
);
DESC ACCOUNTS;
CREATE TABLE TRANSACTIONS (
TRANSACTIONID INT,
TRANSACTIONDATE DATE,
AMOUNT DECIMAL(10,2),
TRANSACTIONTYPE VARCHAR(20)
);
DESC TRANSACTIONS;
CREATE TABLE BRANCHES (
BRANCHID INT,
BRANCHNAME VARCHAR(100),
BRANCHADDRESS VARCHAR(200),
BRANCHPHONE VARCHAR(15)
);
DESC BRANCHES;
CREATE TABLE ACCOUNTBRANCHES (
ASSIGNMENTDATE date);
SHOW TABLES;
CREATE TABLE LOANS (
LOANID INT,
LOANAMOUNT DECIMAL(10,2),
INTERESTRATE DECIMAL(5,2),
STARTDATE DATE,
ENDDATE date);
SHOW TABLES;


